"""add tools column to agents

Revision ID: 9a84045a956f
Revises: 
Create Date: 2025-04-18 14:36:43.374431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a84045a956f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('tools', postgresql.ARRAY(sa.Enum('WEB_SEARCH', 'WEB_SCRAPING', 'WEB_BROWSING', 'FINANCE', 'RESEARCH', 'FILE_READER', 'DATABASE_ACCESS', 'TEXT_GENERATOR', 'IMAGE_GENERATOR', 'SPREADSHEET_TOOL', 'CODE_INTERPRETER', 'EMAIL_ASSISTANT', name='toolenum')), nullable=True))
    op.add_column('agents', sa.Column('description', sa.String(), nullable=True))
    op.drop_constraint('agents_name_key', 'agents', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('agents_name_key', 'agents', ['name'])
    op.drop_column('agents', 'description')
    op.drop_column('agents', 'tools')
    # ### end Alembic commands ###
