import enum


class ToolEnum(enum.Enum):
    WEB_SEARCH = "WEB_SEARCH"
    WEB_SCRAPING = "WEB_SCRAPING"
    WEB_BROWSING = "WEB_BROWSING"
    FINANCE = "FINANCE"
    RESEARCH = "RESEARCH"
    FILE_READER = "FILE_READER"
    DATABASE_ACCESS = "DATABASE_ACCESS"
    TEXT_GENERATOR = "TEXT_GENERATOR"
    IMAGE_GENERATOR = "IMAGE_GENERATOR"
    SPREADSHEET_TOOL = "SPREADSHEET_TOOL"
    CODE_INTERPRETER = "CODE_INTERPRETER"
    EMAIL_ASSISTANT = "EMAIL_ASSISTANT"
